### PR TITLE
Uclibc

### LINKED ISSUE #909: sysrepo does not build on OpenWrt with an older uClibc toolchain
### Description
Sysrepo has 3 bugs when build with older uClibc toolchain:

1)
```
/opt/inteno/iopsys/build_dir/target-arm_xscale_uClibc-0.9.33.2_eabi/sysrepo-e4a5705a4c5293ba121048c71899b98243d99edf/src/common/sr_utils.h:182:48: error: unknown type name 'va_list'
 int sr_vasprintf(char **strp, const char *fmt, va_list ap);
                                                ^
In file included from /opt/inteno/iopsys/build_dir/target-arm_xscale_uClibc-0.9.33.2_eabi/sysrepo-e4a5705a4c5293ba121048c71899b98243d99edf/src/common/sr_common.h:49:0,
                 from /opt/inteno/iopsys/build_dir/target-arm_xscale_uClibc-0.9.33.2_eabi/sysrepo-e4a5705a4c5293ba121048c71899b98243d99edf/src/common/sr_common.c:28:
/opt/inteno/iopsys/build_dir/target-arm_xscale_uClibc-0.9.33.2_eabi/sysrepo-e4a5705a4c5293ba121048c71899b98243d99edf/src/common/sr_mem_mgmt.h:152:86: error: unknown type name 'va_list'
 int sr_mem_edit_string_va(sr_mem_ctx_t *sr_mem, char **string_p, const char *format, va_list args);
                                                                                      ^
make[5]: *** [src/CMakeFiles/COMMON.dir/common/sr_common.c.o] Error 1
```

2)
```
/opt/inteno/iopsys/build_dir/target-arm_xscale_uClibc-0.9.33.2_eabi/sysrepo-e4a5705a4c5293ba121048c71899b98243d99edf/src/common/sr_utils.h:182:48: error: unknown type name 'va_list'
 int sr_vasprintf(char **strp, const char *fmt, va_list ap);
                                                ^
In file included from /opt/inteno/iopsys/build_dir/target-arm_xscale_uClibc-0.9.33.2_eabi/sysrepo-e4a5705a4c5293ba121048c71899b98243d99edf/src/common/sr_common.h:49:0,
                 from /opt/inteno/iopsys/build_dir/target-arm_xscale_uClibc-0.9.33.2_eabi/sysrepo-e4a5705a4c5293ba121048c71899b98243d99edf/src/common/sr_common.c:28:
/opt/inteno/iopsys/build_dir/target-arm_xscale_uClibc-0.9.33.2_eabi/sysrepo-e4a5705a4c5293ba121048c71899b98243d99edf/src/common/sr_mem_mgmt.h:152:86: error: unknown type name 'va_list'
 int sr_mem_edit_string_va(sr_mem_ctx_t *sr_mem, char **string_p, const char *format, va_list args);
                                                                                      ^
make[5]: *** [src/CMakeFiles/COMMON.dir/common/sr_common.c.o] Error 1
```

3)
```
Linking C executable sysrepo-plugind
libsysrepo.so.0.6.0: undefined reference to `mkstemps'
collect2: error: ld returned 1 exit status
```

### PR DESCRIPTION
**Pull request by mislavn**
### Description
Patches to fix broken build in OpenWrt for an older uClibc toolchain. It fixes the problem under 1. and 2.

### Closure
Put closes #909

### CODE REVIEW

**Comment by mislavn** [comment]
Problem 3. is a bit tricky because mkstemps is not defined at all in uClibc. So I have to add custom function definition if mkstemps is missing or change the code logic for sysrepo plugin.

**Comment by michalvasko** [comment]
Hi,
if you want these changes to make it into the release, please fix the problem with macros (as shown by travis compilation). Regarding `mkstemps`, I think it would be fine to use `mktemp`, then add the suffix and open the file as an implementation of `mkstemps` on systems that do not have it. That is quite easy to implement.

Regards,
Michal

**Comment by mislavn** [comment]
Hi Michal,

I am working on the macro issue, for the mkstemps issue I am OK with that solution because it would be rarely used (only when mkstemps is not available). An alternative would be to create a file and a socket, the file would be a check of uniqueness, and when the socket is unlinked I would delete the file.

Regards,
Mislav

**Comment by mislavn** [comment]
Hi Michal,

I made the changes but the build fails and I'm not sure why.

Regards,
Mislav

File: src/clientlib/cl_subscription_manager.c [hunk 1]
```diff
@@ -1447,13 +1447,24 @@ cl_sm_get_server_socket_filename(cl_sm_ctx_t *sm_ctx, const char *module_name, c
...
     }
+#else
+    /* append temporary file name part */
+    strncat(path, ".XXXXXX", PATH_MAX - strlen(path) - 1);
+    fd = mkstemp(path);
+    if (-1 != fd) {
+        close(fd);
+        unlink(path);
+    }
+    strncat(path, ".sock", PATH_MAX - strlen(path) - 1);
```
Comment (michalvasko) [inline src/clientlib/cl_subscription_manager.c]: I think that when you add ".sock" to the path here, it does not actually change the opened file, why should it? That means that ".XXXXXX" file will be created and opened, but socket_path will be ".XXXXXX.sock" so it will fail to find the socker or am I mistaken? That is why I suggested to use mktemp, not mkstemp.

File: src/clientlib/cl_subscription_manager.c [hunk 2]
```diff
@@ -1447,13 +1447,24 @@ cl_sm_get_server_socket_filename(cl_sm_ctx_t *sm_ctx, const char *module_name, c
...
     fd = mkstemps(path, 5);
     if (-1 != fd) {
         close(fd);
         unlink(path);
     }
+#else
+    /* append temporary file name part */
+    strncat(path, ".XXXXXX", PATH_MAX - strlen(path) - 1);
+    fd = mkstemp(path);
+    if (-1 != fd) {
```
Comment (michalvasko) [inline src/clientlib/cl_subscription_manager.c]: I know it was like this before but it is not correct, so when you are modifying this code, it would be best if we added a correct error check. If `fd == -1` the whole function should fail I think.

**Comment by michalvasko** [comment]
Hi Mislav,
I submitted a review, but regarding failing tests, we will look at it and fix it, do not trouble yourself with it, it is independent of your pull request.

Regards,
Michal

File: src/clientlib/cl_subscription_manager.c (hunk 2 above)
Comment (mislavn) [inline src/clientlib/cl_subscription_manager.c]: OK.

File: src/clientlib/cl_subscription_manager.c (hunk 1 above)
Comment (mislavn) [inline src/clientlib/cl_subscription_manager.c]: Sorry I forgot to finish the patch, I did the changes now.
I am not sure if the open flags are correct can you take a look.

**Comment by michalvasko** [comment]
Hi Mislav,
I committed what I meant by those error checks, no matter. Also, the tests passed now, it was a libyang problem.

Regards,
Michal

**Comment by mislavn** [comment]
Hi Michal,

thank you.

Regards,
Mislav
